# Site settings
title: Monkey Mart Games
description: Play free online games at Monkey Mart
url: https://monkeymart.one
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - node_modules
  - package.json
  - package-lock.json

# Custom headers
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

# 404 page
defaults:
  - scope:
      path: "404.html"
    values:
      permalink: /404.html

# GitHub Pages settings
github:
  is_project_page: false

# Custom 404 page
defaults:
  - scope:
      path: "404.html"
    values:
      permalink: /404.html

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - server.js
  - server.py
  - package.json
  - package-lock.json
  - node_modules 