# Site settings
title: Monkey Mart Games
description: Play free online games at Monkey Mart
url: "https://monkeymart.one"
baseurl: ""

# Build settings
include: [".well-known"]
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - node_modules
  - package.json
  - package-lock.json
  
# SEO settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom headers
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

# 404 page
defaults:
  - scope:
      path: "404.html"
    values:
      permalink: /404.html

# GitHub Pages settings
github:
  is_project_page: false

# Exclude files
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - server.js
  - server.py
  - package.json
  - package-lock.json
  - node_modules

# Custom 404 page
defaults:
  - scope:
      path: "404.html"
    values:
      permalink: /404.html

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - server.js
  - server.py
  - package.json
  - package-lock.json
  - node_modules 